### ISSUE TITLE
Missing web feed (Atom or RSS) for blog posts

### ISSUE THREAD

**Issue by k0ral** [Ypnose/wswsh#9]
I couldn't find a RSS or Atom feed for https://ywstd.fr/blog/, let alone a `<link rel="alternate">` tag.
Might be intended, might not be, I figured I would raise the point anyway :) .

**Comment by Ypnose** [comment]
Good evening,
Thanks for your message and sorry for the huge delay, it was not on purpose.  One year ago to the day (almost), Atom feed was actually removed from `wswsh` (513a566e71790458e). I did it because it seemed to me that my articles were kinda ignored and also because the code was kinda bloated. Glad to see there is at least one person requesting the feed ! :)
If you are one of those mysterious readers and think it would be better, I could find a few hours in that lockdow in order to write a local script. It would make your life easier ?

**Comment by k0ral** [comment]
> If you are one of those mysterious readers

Guilty as charged ! :)

> and think it would be better

It seems useful to have a standard, script-friendly way of retrieving blog articles. Whether it's implemented as an Atom/RSS feed, or through another standard, doesn't matter much to me. I suggested Atom/RSS because it's the only game in town that I know of, but if you can think of a more modern alternative, I'd be happy to use it as well.

> PS: Your avatar reminds me all those hours spent in Neverwinter Nights 2. Good old days.

You and me both. Next step: listen to the main theme, and remember all those hours spent just in creating a character.
You're welcome :) .

**Comment by Ypnose** [comment]
As I know Atom quite a bit and like how it's not so bloated compared to RSS, I wrote a script to generate the feed. It was quite funny to do actually (as always with `awk`). I'm satisfied with the final result. It was also validated as an Atom 1.0 feed.
Would you mind to take a [look](https://ywstd.fr/blog/atom.xml), please ? Let me know if it fits your need.

About Neverwinter Nights OST, I advice you to listen to Mask of the Betrayer OST. Despite the Spirit thing crap, the atmosphere of that game is outstanding.

**Comment by k0ral** [comment]
- [x] Blog page advertises feed through a `<link rel="alternate">`
- [x] HTTP response for feed mentions `Content-Type: text/xml`
- [x] Feed is valid with respect to Atom standards (my parser succeeded)
- [x] Feed items link to blog posts (my parser recognized 12 blog posts)

Looks neat to me, thank you !

> About Neverwinter Nights OST, I advice you to listen to Mask of the Betrayer OST. Despite the Spirit thing crap, the atmosphere of that game is outstanding.

Haven't played that one, so OST expectedly doesn't elicit as many emotions on my side. Definitely on my to-play list, though.
